version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gptrue-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - gptrue-network

  redis:
    image: redis:alpine
    container_name: gptrue-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gptrue-network

networks:
  gptrue-network:
    driver: bridge

volumes:
  redis-data:
