version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run start:dev
    networks:
      - gptrue-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - gptrue-network

volumes:
  redis-data:

networks:
  gptrue-network:
    driver: bridge
