export const TEST_TOKENS = {
  ORCHESTRATOR_SERVICE: 'ORCHESTRATOR_SERVICE',
  SEMANTIC_CACHE_SERVICE: 'SEMANTIC_CACHE_SERVICE',
  QUERY_GENERATOR_SERVICE: 'QUERY_GENERATOR_SERVICE',
  QUERY_VALIDATOR_SERVICE: 'QUERY_VALIDATOR_SERVICE',
  RESPONSE_GENERATOR_SERVICE: 'RESPONSE_GENERATOR_SERVICE',
  FEEDBACK_SERVICE: 'FEEDBACK_SERVICE',
} as const;
